from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState

# 导入统一日志系统
from tradingagents.utils.logging_init import get_logger
logger = get_logger("default")


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        str, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        str, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # 🔧 死循环修复: 工具调用计数器
    market_tool_call_count: Annotated[int, "Market analyst tool call counter"]
    news_tool_call_count: Annotated[int, "News analyst tool call counter"]
    sentiment_tool_call_count: Annotated[int, "Social media analyst tool call counter"]
    fundamentals_tool_call_count: Annotated[int, "Fundamentals analyst tool call counter"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]

    # ============ 指数预测模块新增字段 ============
    target_index: Annotated[str, "Current index code being analyzed (e.g. 000300.SH)"]
    target_indices: Annotated[Sequence[str], "List of all target index codes to analyze"]
    user_expectations: Annotated[Sequence[dict], "List of user's subjective expectations for injection into analyst prompts"]

    # 指数预测分析师报告
    index_market_report: Annotated[str, "Report from the Index Market Analyst"]
    sector_rotation_report: Annotated[str, "Report from the Sector Rotation Analyst"]
    macro_policy_report: Annotated[str, "Report from the Macro Policy Analyst"]

    # 指数分析工具调用计数器
    index_market_tool_call_count: Annotated[int, "Index market analyst tool call counter"]

    # 最终预测结果
    index_prediction_result: Annotated[dict, "Final index prediction result containing all analysis outputs"]


class IndexDebateState(TypedDict):
    bull_history: str
    bear_history: str
    history: str
    current_response: str
    judge_decision: str
    count: int


class IndexRiskDebateState(TypedDict):
    risky_history: str
    safe_history: str
    neutral_history: str
    history: str
    latest_speaker: str
    current_risky_response: str
    current_safe_response: str
    current_neutral_response: str
    judge_decision: str
    count: int


class IndexPredictionState(MessagesState):
    user_expectations: str
    target_indices: str
    trade_date: str
    index_technical_report: str
    index_sentiment_report: str
    macro_policy_report: str
    index_valuation_report: str
    sector_theme_report: str
    index_impact_report: str
    index_debate_state: IndexDebateState
    index_investment_plan: str
    index_trading_plan: str
    index_risk_debate_state: IndexRiskDebateState
    final_index_decision: str
    sender: str
    tech_tool_call_count: int
    sentiment_tool_call_count: int
    macro_tool_call_count: int
    valuation_tool_call_count: int
    sector_tool_call_count: int
    impact_tool_call_count: int
